from .Compra import CompraController
from .Compra import ComprasController
from .Producto import ProductoController
from .Producto import ProductosController
from .ProductoCompra import ProductoCompraController
from .ProductoCompra import ProductosComprasController
from .Cliente import ClienteController
from .Cliente import ClientesController
from .Usuario import UsuarioController
from .Usuario import UsuariosController